# Generated by Django 2.0.7 on 2018-08-01 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_auto_20180430_0016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='ticker',
            new_name='ticker_symbol',
        ),
    ]
