# Generated by Django 2.0.4 on 2018-04-30 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorites',
            old_name='stock',
            new_name='ticker',
        ),
    ]
