# Generated by Django 2.0.7 on 2018-08-03 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='creator',
            new_name='user',
        ),
    ]
