# Generated by Django 2.0.7 on 2018-08-04 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_auto_20180802_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='s_close',
            field=models.IntegerField(default=1.0),
        ),
        migrations.AddField(
            model_name='stock',
            name='s_high',
            field=models.IntegerField(default=1.0),
        ),
        migrations.AddField(
            model_name='stock',
            name='s_low',
            field=models.IntegerField(default=1.0),
        ),
        migrations.AddField(
            model_name='stock',
            name='s_open',
            field=models.IntegerField(default=1.0),
        ),
    ]
