# Generated by Django 2.0.7 on 2018-08-04 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_auto_20180803_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='s_low',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
    ]
