# Generated by Django 2.0.7 on 2018-08-04 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_auto_20180804_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='s_close',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stock',
            name='s_high',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stock',
            name='s_open',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
    ]
